### ISSUE TITLE
Highlight text analysis curricula from beyond the Carpentries

### ISSUE THREAD

**Issue by chennesy** [LibraryCarpentry/governance#35]
**Goals**
Create outlets for sharing open text analysis curricula and emerging text mining tools with LC communities. Explore opportunities for collaboration with organizations such as [Constellate](https://ithaka.github.io/tdm-notebooks/book/all-notebooks.html) and the [HathiTrust Research Center](https://wiki.htrc.illinois.edu/display/COM/Getting+started). 

**Background**
There are growing repositories of high quality teaching materials related to text mining/analysis from outside of the Carpentries, many of which could serve well as extended curriculum for LC workshops. There may also be opportunities to connect more strategically with platforms that enable the text mining of vast digital libraries (e.g., JSTOR, HathiTrust), for possible integration with future LC lessons.

I hope to work with other members of LCAG in 2021/22 to identify and share related curricula with LC communities and to have discussions with potential partner organizations about possible future collaboration.

**Milestones**

- [ ] Identify LCAG members interested in working on these goals
- [ ] Define text analysis curricula that are in scope 
- [ ] Identify other library organizations/platforms working in these spaces
- [ ] Create an outlet or outlets (such as curricular paths, panel discussions, blog posts...) to highlight text analysis curricula for LC communities
- [ ] Initiate conversation(s) with potential partner organizations about future collaborations or integration

**Comment by sarasrking** [comment]
Happy to help out with this @chennesy

**Comment by egrguric** [comment]
Happy to help and cross pollinate from [#36](https://github.com/LibraryCarpentry/governance/issues/36)

**Comment by Fillstar** [comment]
Also keen to gatecrash on this one @egrguric & @sarasrking - i've used a closed envronment with proquest TDM studio and would love to apply the same concepts to open works - happy to chip in if its useful :)

**Comment by nkelber** [comment]
I'm ready for this conversation!
